Authorization과 Login 통합, 비밀번호 변경 후 logout
f-lab-edu/Soccer-Friend pull request #7
Opened 2022-10-19 07:52 UTC by xeonu

issue #3 

Authorization을 controller에서 처리해서 순환참조 문제를 해결했습니다.

### 변경사항
- AuthroizeService와 LoginService 통합
- 비밀번호 변경 후 로그아웃 처리

2022-10-19 11:15 UTC, f-lab-dev commented on src/main/java/soccerfriend/controller/MemberController.java
> +        memberService.delete(memberId);
이제 발견했네요. `delete`는 서비스 관점의 용어일까요? 데이터 관점의 용어일까요?
`Service`는 어떤 레이어의 클래스인가요?

2022-10-19 11:15 UTC, f-lab-dev commented on src/main/java/soccerfriend/service/AuthorizeService.java
> +    public static final String LOGIN_MEMBER = "loginMember";
키를 정하는 선택권은 이 인터페이스를 구현하는 곳에 위임하는게 나을 것 같네요~
이건 세션키를 정하는 것 같으니까요

그리고 `AuthorizeService.LOGIN_MEMBER` 라는 표현은 다른 개발자가 보았을때 어떤 용도인지 명확히 파악하기 힘들 것 같습니다~

2022-10-19 11:15 UTC, f-lab-dev commented on src/main/java/soccerfriend/service/SessionAuthorizeService.java
>          return (String) httpSession.getAttribute(LOGIN_MEMBER);
로그인이 안되어있으면 null이 반환될 것 같은데 의도하신 것일까요?

2022-10-19 11:15 UTC, f-lab-dev commented on src/main/java/soccerfriend/service/SessionAuthorizeService.java
> +            throw new PasswordIncorrectException(PASSWORD_INCORRECT);
아이디가 틀렸는지, 비밀번호가 틀렸는지 굳이 알려줄 필요가 있을까요?
요즘 서비스들은 어떻게 구현되어있을까요?

2022-10-20 04:13 UTC, xeonu commented on src/main/java/soccerfriend/controller/MemberController.java
> +        memberService.delete(memberId);
둘다 해당된다고 생각했습니다. github 내에서도 delete account라고 표현하고 있습니다. 다른 표현도 있는지 한번 찾아보고 필요하면 수정해보겠습니다. 
service는 비즈니스 레이어에 속해있으며 비즈니스 로직만을 담아야합니다.

2022-10-20 04:14 UTC, xeonu commented on src/main/java/soccerfriend/service/AuthorizeService.java
> +    public static final String LOGIN_MEMBER = "loginMember";
따로 분리해보도록 해보겠습니다.

2022-10-20 04:15 UTC, xeonu commented on src/main/java/soccerfriend/service/SessionAuthorizeService.java
>          return (String) httpSession.getAttribute(LOGIN_MEMBER);
이 부분은 앞으로 발전시켜야 될 부분이 많습니다. 로그인 유지를 위해서도 사용될 수 있습니다. null일 경우 exception을 발생시키는 코드를 추가해야겠습니다.

2022-10-20 04:16 UTC, xeonu commented on src/main/java/soccerfriend/service/SessionAuthorizeService.java
> +            throw new PasswordIncorrectException(PASSWORD_INCORRECT);
틀리면 그냥 틀렸다고 알리는 것이 나을 것 같습니다. 틀린 사유를 알려주면 해커 혹은 도용자에게 도움을 주는 행위같네요.

2022-10-21 10:23 UTC, f-lab-dev approved these changes
아 이거는 조금 늦게 리뷰드리자면 회원탈퇴를 할 때 바로 DB에서 삭제하지 않습니다~
탈퇴처리를 어떻게 하는지 사례를 찾아보시면 좋을 것 같아요
(별도의 이슈로 빼도 좋습니다)

2022-10-21 10:23 UTC, f-lab-dev requested changes
아 코멘트를 잘못달았는데 리뷰달린건 수정해주세요~

2022-10-21 10:23 UTC, f-lab-dev commented on src/main/java/soccerfriend/service/SessionAuthorizeService.java
>          return (String) httpSession.getAttribute(LOGIN_MEMBER);
왜 exception을 던져야할까요?

2022-10-21 10:56 UTC, xeonu commented
탈퇴 구현은 임시보관기관을 고려해 다른 테이블에 저장하는 방향이 떠오르네요, 다른 프로젝트는 어떻게 구현했는지 한번 참고해보겠습니다. 추가적으로 코드리뷰 반영은 다른 PR에서 확인할 수 있습니다.

2022-10-21 10:59 UTC, xeonu commented on src/main/java/soccerfriend/service/SessionAuthorizeService.java
>          return (String) httpSession.getAttribute(LOGIN_MEMBER);
서버 오류로 세션저장소가 사라져서 로그인된 클라이언트가 로그인 정보가 필요한 서비스를 이용할 수도 있어서 따로 예외처리를 해줘야합니다. 프론트 측에서는 다시 로그인하는 방향으로 규현할 수 있겠네요.

2022-10-21 11:11 UTC, merged